version: '3.8'

services:
  app:
    image: jjmendez/sgtech-rrhh:latest
    container_name: app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: sgtech_rrhh_app
      DB_USERNAME: sgtech_app_user
      DB_PASSWORD: SgTechP@ss2025
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
